version: '3.8'

services:
  azure-cost-dashboard:
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_REDIRECT_URI=${AZURE_REDIRECT_URI}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    env_file:
      - ../../.env
    volumes:
      # Mount source code for development (remove in production)
      - ../../:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s