name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate application structure
        env:
          # Provide dummy envs to satisfy imports
          AZURE_CLIENT_ID: dummy
          AZURE_TENANT_ID: dummy
          AZURE_CLIENT_SECRET: dummy
          AZURE_REDIRECT_URI: http://localhost:5000/auth/callback
          FLASK_SECRET_KEY: testsecret
        run: |
          source venv/bin/activate
          python -c "from backend.azure import cost; print('✅ Cost module imports successfully')"
          python -c "from backend.auth import azure_auth; print('✅ Auth module imports successfully')"
          python -c "from backend.api import routes; print('✅ API routes import successfully')"
          python -c "import app; print('✅ Main app imports successfully')"
          echo "✅ All modules import successfully - application structure is valid"
